new_questions = [
    "Reflect on life | 人生について反省する",
    "Obtain a deeper connection in life | 人生でより深い繋がりを得る",
    "Opportunity for self-discovery | 自己発見の機会",
    "Get in touch with my true self | 真の自分と触れ合う",
    "Find inspiration in natural surroundings | 自然環境の中でインスピレーションを見つける",
    "Chance to think/solve problems | 問題を考える/解決するチャンス",
    "Stimulate creativity | 創造性を刺激する",
    "Develop a sense of self-confidence | 自信を育む",
    "Recreate in a primitive environment | 原始的な環境でのレクリエーション",
    "Observe and appreciate the ecosystem | 生態系を観察し、感謝する",
    "Explore the natural environment | 自然環境を探検する",
    "Experience nature's magic and mysticism | 自然の魔法と神秘主義を体験する",
    "Develop a oneness with nature | 自然との一体感を育む",
    "Experience the scenic quality of nature | 自然の景観の質を体験する",
    "Feel connected to a place that is important | 重要な場所とのつながりを感じる",
    "Being alone/solitude | 一人でいること/孤独",
    "Free from observation from all other people | 他のすべての人々の観察から自由である",
    "Get away from daily routines | 日常のルーチンから離れる",
    "Tranquility and peace | 静けさと平和",
    "Simplify daily priorities | 日々の優先順位を簡素化する",
    "Physical health and exercise | 身体の健康と運動",
    "Experience a sense of community with other pilgrims | 他の巡礼者とのコミュニティ感覚を体験する",
    "Be in a small intimate group | 小さな親密なグループにいる",
    "Feel a connection with others who value wilderness and remote places | 荒野と遠隔地を価値あるものとする他の人々との繋がりを感じる",
    "Having a sense of discovery | 発見の感覚を持つ",
    "Having an adventure | 冒険をする",
    "Physical challenge | 身体的な挑戦",
    "Develop my religious values | 自分の宗教的価値観を発展させる",
    "Meet local non-pilgrims along the route | ルート上の地元の非巡礼者に会う",
    "Have a story to tell | 語るべき物語がある",
    "Religious experiences | 宗教的体験",
    "Experience places that I have read or been told about | 読んだり聞いたりした場所を体験する",
    "The religious heritage of the trail | トレイルの宗教的遺産",
    "Visit shrines or other religious buildings | 神社やその他の宗教的建造物を訪れる",
    "Travel in a slow pace | ゆっくりとしたペースで旅をする",
    "Reach the holy shrines of Kumano Kodo (Hongu, Shingu or Nachi) | 熊野古道（本宮、新宮、那智）の神聖な神社に到達する",
    "Getting to know with foreign places and landscapes | 外国の場所や風景を知る",
    "Travel in an environment-friendly way | 環境に優しい方法で旅をする",
    "Spiritual experiences | 霊的な体験",
    "Buying/consuming local products (like foods or crafts) | 地元の製品（食品や工芸品など）を購入/消費する",
    "Visit local communities | 地元のコミュニティを訪れる",
    "The ancient heritage of the trail | トレイルの古代の遺産",
    "Heritage sites along the trail (shrines, temples, historical landmarks, etc.) | トレイル沿いの遺産サイト（神社、寺院、歴史的ランドマークなど）",
    "Develop my spiritual values | 自分の霊的価値を発展させる",
    "Meditative experiences | 瞑想的な体験",
    "Be in the present | 現在にいる",
    "Follow the rhythms of nature and landscape | 自然と風景のリズムに従う",
    "Feel free to take my time | 自分の時間を自由にとる",
    "Discover my inner time | 自分の内なる時間を発見する",
]
